import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { execSync } from 'node:child_process'

const localSpec = resolve('docs/openapi.yaml')
const legacySpec = resolve('../backend/docs/openapi.yaml')
const outputDir = resolve('src/api/generated')
const baseUrl = process.env.API_BASE_URL || process.env.VITE_API_BASE_URL

let specSource = ''

if (existsSync(localSpec)) {
  specSource = localSpec
} else if (existsSync(legacySpec)) {
  specSource = legacySpec
} else if (baseUrl) {
  specSource = `${baseUrl.replace(/\/$/, '')}/openapi.json`
}

if (!specSource) {
  console.error('OpenAPI spec not found.')
  console.error('Expected docs/openapi.yaml or ../backend/docs/openapi.yaml, or set API_BASE_URL to use /openapi.json.')
  process.exit(1)
}

mkdirSync(outputDir, { recursive: true })

execSync(`npx openapi-typescript "${specSource}" -o "${resolve(outputDir, 'schema.ts')}"`, {
  stdio: 'inherit',
})

writeFileSync(
  resolve(outputDir, 'README.md'),
  `# Generated API Types\n\nThis folder is generated by npm run api:gen. Do not edit manually.\n`,
)
